Add Predef
slamdata/slamdata-predef pull request #1
Opened 2017-02-16 06:28 UTC by drostron

Depends on slamdata/sbt-slamdata#1

2017-02-22 14:15 UTC, sellout requested changes
Some cleanup to the Predef, and otherwise just need to get the other PR merged so this can pass its build.

2017-02-22 14:15 UTC, sellout commented on src/main/scala/slamdata/Predef.scala
>    type Iterable[+A] = C.Iterable[A]
Get rid of this one.

2017-02-22 14:15 UTC, sellout commented on src/main/scala/slamdata/pkg/PackageAliases.scala
>  @SuppressWarnings(scala.Array("org.wartremover.warts.MutableDataStructures"))
If you check out the edits for this file (and PackageMethods) in https://github.com/quasar-analytics/quasar/compare/master...sellout:sql-distinct#diff-91eff94d671cb9207858b1d3f4d061d0 you can get rid of this Suppression and a bunch of other things that shouldn’t be in our Predef.

2017-02-22 15:12 UTC, drostron commented on src/main/scala/slamdata/pkg/PackageAliases.scala
>  @SuppressWarnings(scala.Array("org.wartremover.warts.MutableDataStructures"))
Excellent, will ✄ accordingly.

2017-02-23 20:27 UTC, drostron commented
@sellout Ready for another look

2017-02-23 20:36 UTC, sellout approved these changes

2017-02-23 20:37 UTC, merged